import type { Metadata } from "next";

import "./globals.css";


import { Poppins } from "next/font/google";

import Header from "../components/ui/header/header";
import Footer from "../components/ui/footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // choose what you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="">
          <Header />
          {children}
        </main>
        <footer className="bg-black">
          <Footer />

          
        </footer>
      </body>
    </html>
  );
}
